### ISSUE TITLE
[infra/ServerBuild] 서버 구축

### ISSUE THREAD

**Issue by Qbeom0925** [PomeTeam/POME_Server#1]
- [x] AWS EC2 구축 
- [x] AWS RDS 구축
- [ ] dev/prod 서버 이중화
- [ ] dev/prod DB 이중화
- [x] Jenkins, Docker 구현

**Comment by dldmsql** [comment]
[EC2 Ubuntu에서 Docker 설치하기](https://velog.io/@haeny01/AWS-EC2-X-Docker) 해당 블로그 참고

도커 실행 중, 권한 오류 발생 시 [도커 권한 오류 해결](https://dongle94.github.io/docker/docker-permission-error/) 해당 블로그 참고

[EC2에서 젠킨스 설치하기](https://hyunmin1906.tistory.com/272) 해당 블로그 참고

[젠킨스 CICD 구축하기](https://velog.io/@haeny01/AWS-Jenkins%EB%A5%BC-%ED%99%9C%EC%9A%A9%ED%95%9C-Docker-x-SpringBoot-CICD-%EA%B5%AC%EC%B6%95#-docker-%EC%84%A4%EC%B9%98) 해당 블로그 참고

[젠킨스 publish over ssh 설정하기](https://minsoolog.tistory.com/45) 해당 블로그 참고
